### ISSUE TITLE
Issue 09 - Article: Freeform article about DAOs

### ISSUE THREAD

**Issue by Smokyish** [aragon/aragon-monthly#152]
# Request for content

### Request type:
Article

#### Content type:
Opinion piece

### Description of the requested content
Thoughtful, freeform article on the subject `DAOs`. You have the freedom to write an editorial piece of your choosing.

**Article must be original content created for this purpose and not published anywhere before this**.

> An opinion piece is an article that mainly reflects the author's opinion about the subject. Opinion pieces in the newspaper are often written by a subject-matter expert, a person with a unique perspective on an issue.

### Additional information
Minimum 1500 words, maximum 2500 words

#### Deadline
By the end of August, in time for Aragon Monthly issue 09
___
## Notes

We will allow for a **maximum of 3 revisions** to the Pull Request based on feedback given by the Monthly staff, if the PR still doesn't meet the quality and standard, we will close the PR.

This issue **should be finished and merged as soon as possible**, this is first-come, first-served; the first proper Pull Request will be merged and will be awarded the associated bounty.

**Comment by status-open-bounty** [comment]
![Contract deploying](https://openbounty.status.im/img/deploying_contract.png)
Transaction: [0xb10ce4ed9ab5aa4ab66b74703f691c4b15b4201324b9617469d0c0448d5d8e19](https://etherscan.io/tx/0xb10ce4ed9ab5aa4ab66b74703f691c4b15b4201324b9617469d0c0448d5d8e19)

**Comment by csggene3** [comment]
Sorry for submitting the pull request incorrectly and changing the master. As a first time issue I'd like to give this a shot if that is agreeable. I'm assuming by the end of August no longer applies, but I'll hope to have a first draft to you by tonight or tomorrow unless anyone objects to me trying this.

**Comment by Smokyish** [comment]
@csggene3 Hi, happy to see you're interested in contributing!

Do feel free to submit a Pull Request with the complete article and we will review it and comment with any possible feedback!

And don't worry about the timeline, if it's not on time for Issue 09, i will just move it to the next issue :)

**Comment by csggene3** [comment]
Thanks man, will do.

**Comment by csggene3** [comment]
ICOs are for Fraud, DAOs are for Function

The last two years have seen a precipitous rise and fall in the both the price of cryptocurrencies like Bitcoin and Ethereum amongst many new others branded as ICOs (or initial coin offerings) as well as a general awareness of their existence and the broader underlying ecosystems that accompany them. Many this year are quite upset with their purchases from last year due to the steep drop off in associated prices. The perception is that software developers created simple tokens on the various issuing blockchains (like Ethereum, NEO, Cardano, Ethereum Classic, etc) that served little more purpose than to act as a form of quick and dirty security issuance, or "penny stock," with little oversight or regulation, and then cashed out large groups of shares for themselves, ostensibly to fund future software development of their projects, but truthfully or more likely to enrich themselves greatly with no intention or obligation for their promises to the public or their own investors to be kept. There are hundreds of similar projects like these with similar accusations against their progenitors and "developers," or dismissed as " honest failures due to diminished market conditions," yet these types of blatant excuses fall on the deaf ears of the thousands that lost out and the many other honest developers than knew better.

Back in July of 2014, Vitalik Buterin, the brain child behind Ethereum, led a crowdsale issuing 2000 ETH for each 1 BTC valued at around $600/BTC at the time, and raised 3700 BTC in the course of 12 hours, raising about $2.3 million USD in that time period setting the stage for a grand capitalization project. I highlight the Ethereum crowdsale to bring attention to the point of this article, the DAO (or decentralized autonomous organization) and the first effort at such an organizational structure and concept. "TheDAO," as it is now infamously known, began raising capital in May of 2016 and quickly reached the dizzying heights of $150 million USD within that single month from just 11,000 investors. Ethereum's power is in the ability to drive "smart contracts" that function through the blockchain-based virtual machine Buterin envisioned as the perfect compliment to Bitcoin. Bitcoin is essentially a store of value, likened by Buterin to gold whereas he likens Ethereum to oil, providing energy to the "smart contracts."

The DAO is essentially a special form of smart contract that creates a virtual organization, providing a predefined function or set of functions without the need to employ a large-scale permanent staff to receive or distribute funds, removing the conflict of trust and significantly reducing operational overhead. Though a DAO can operate as a profitable venture, the majority of current DAOs serve charitable functions such as decentralized governance, poverty reduction, and other "broader good" purposes that can make up the backbone of the evolving blockchain ecosystem. 

Getting back to the case of the original "TheDAO," a small programming error in the smart contract allowed for a significant amount of the funds to be stolen by an unknown hacker or group of hackers. Usually in the case of cryptocurrency, stolen funds on a blockchain cannot be reversed and are then in essence gone permanently without recourse, but in certain situations if enough holders vote to "hardfork" the currency or the contract, the stolen funds can be stranded in a way that keeps them from being spendable or withdrawn. The Ethereum community discussed their options and decided to hardfork the token, leading to a split in the blockchain and creating 2 currencies, Ethereum and Ethereum Classic, while disabling the hacker as well. A heroic band of developers comprised of some of the original smart contract writing members who created the bug, called themselves WHG, or the White Hat Group, and were led by Griff Green to be able to review the original code, patch the errors, and begin to recover the stolen funds by creating some new smaller contracts that would help users recover what they lost individually. This was a black spot on the record of Ethereum and the DAO concept in general, but demonstrated valuable lessons that could be learned and worked out worst case scenarios with functional solutions offered, drastic though they might have been.

Griff Green has gone on to found a truly remarkable new DAO called Giveth that focuses on building the infrastructure to enable charitable purposes of all shapes and sizes. "Blockchain4Good" is their mantra, and they have over a dozen different communities and campaigns that look to make an impact serving any social good imaginable, with more in the pipeline and anyone with the desire eligible to create their own. Aragon is another one of their DACs (or decentralized autonomous communities) that focuses on providing social benefit through novel concepts and coordination with like minded developers that want to make a difference in the world without sacrificing their principles to work for a prototypical corporate overlord. Doing charitable work doesn't necessarily mean working for free, and these organizations have already received grants while continuing to be eligible for funding from larger organizations like the Ethereum Foundation as well as none blockchain based corporations and organizations like banks, the UN, and UNICEF.

The true power of the DAO lies in replacing the traditional infrastructure of charitable foundations and non-profit corporations around the world, as well as potentially government legislative bodies and voting or election mechanisms. Let's start with the non-profit corporation. Many think that non-profits are judged primarily by the social good they intend to do, like curing cancer, ending human trafficking, or saving the rain forests. While this metric is noble in and of itself, it does little to complete the broader picture of how well they accomplish these goals. Cancer still isn't cured, human trafficking still exists, and the rain forests are still burning. The truest measure of how well a non-profit accomplishes its stated purpose is to look at the proportion of donations they receive each year to their spending on maintaining their own existence, commonly referred to as overhead. Many ostensibly well meaning organizations spend a giant portion of their yearly donations in a wasteful, and none transparent manner, with very large non-profits very commonly spending more than 50% yearly on staff salaries, office spaces, office equipment, and even luxuries that are completely disconnected from their mission statement. While there are many good organizations that do a good job of benefiting the public, there are no organizations that spend nothing on expenses. There are many websites that track this spending, and some perform better than others, but this is where the DAO structure outperforms the potential of any organizational body. As long as the software is in place, funds can be placed within the smart contract, and their intended use can be dedicated to the stated purpose, in a trust free fashion, with no overhead to speak of. Charitable funds can be dispensed to their intended targets through crypto currency wallets without the need for money to change hands. Items can be purchased and shipped to whomever and wherever they are needed without the need for a middleman. Donations can be accumulated, tracked in a central location, and followed to their end use point without requiring the trust or touch of a human being at any point.

Decentralized governance is also on the horizon with these same structures. Tokens can serve as voting rights or weight of votes, replacing the need for polling station, physically counting ballots, or trusting the integrity of the people involved. Campaign finance issues can be heavily curbed by removing the need for all that overhead and limiting the distribution of information to those known to hold the token voting rights, removing the need for shotgun style political or legislative advertising. Trust of government systems and legislative bodies can be restored by replacing human beings whose only purpose is to cast a vote with a trust free model that takes its direction from a smart contract that can be relied upon to do exactly what it is supposed to, is available all day, everyday, and is never swayed by money, favors, or other forms of untoward political influence. Politicians, campaign finance, physical infrastructure, and other forms of needless spending can be done away with in favor of a transparent model that has little to no overhead, and can be trusted to do exactly what the code says it will do, every time.

The DAO is the solution to almost every organizational challenge society faces today. The monies that could be cumulatively dedicated to DAO versions of the world's current organizations would perform so much more good than presently possible, the positive results are almost inconceivable. The potential to convert beings to code and allow the DAO to perform their job more efficiently and in a trust free manner will change the world. If we are honest with ourselves and each other, we should strive to understand these opportunities and implement them in our own communities and with our own ideas as soon as humanly possible.

**Comment by csggene3** [comment]
I'm sorry I'm so terrible at GitHub, I really don't know how to submit the pull request appropriately obviously.
