### ISSUE TITLE
Issue 01 - Article: How can Aragon help create a fairer world

### ISSUE THREAD

**Issue by Smokyish** [aragon/aragon-monthly#8]
# Request for content

### Request type:
Article

#### Content type:
Opinion Piece

### Description of the requested content
Thoughtful article on the subject `How can Aragon help create a fairer world`.
The article should delve into the technological revolution that the blockchain technology has ushered in and how decentralized autonomous organizations can help people in repressed regions of the world.

### Additional information
Minimum 500 words, maximum 1500 words

#### Deadline
By the end of January, in time for Aragon Monthly issue 01

**Comment by status-open-bounty** [comment]
![Contract deploying](https://openbounty.status.im/img/deploying_contract.png)
Transaction: [0x33bf0f889dd18ae71cf822b97a337e814a26ad2fb5da736f4830f963e982a95b](https://etherscan.io/tx/0x33bf0f889dd18ae71cf822b97a337e814a26ad2fb5da736f4830f963e982a95b)

**Comment by KingJibar** [comment]
Greetings Aragon, 

I Submit "Aragon and The Future of Governance" for This Bounty. 

Here is The Link:

https://docs.google.com/document/d/1WRqTsVa873r9Pwdoib0qiVE9K0N70RT3YtvT9887Lug/edit?usp=sharing

May you Never Know Poverty, 

- King Jibar, Dyno Empire

**Comment by Smokyish** [comment]
@KingJibar This is not a Pull Request to claim to bounty and it is not a thoughtful high quality article rather than a list of sentences, so for these reasons it won't be considered for the bounty.

**Comment by Zurpples** [comment]
How can Argon create a fairer world?
Suddenly it’s 2020. We gaze over a border station across the DMZ. This is a land that was thought to be beyond law or justice. Now (due to tokenization and the Argaon blockchain) things are looking up. A new hotel gleams in the distance of a new city where North and South are collaborating. The entire map of the city (and who did what) is stored securely in the blockchain, crypto is the currency of the region, and people trying to get rich off of exploitation are quickly found out. The goal is to relocate workers from a labor camp here to rebuild their lives. It once seemed impossible, now the only question is how quickly the goal can be accomplished. The workers vote on what the most important tasks to accomplish will be. They set their own timelines, and several of them from “up north” even set their own wages (lower than the expected pay) to get a foot in the door.

In Nepal Argon is powering different watchtowers with the goal of preventing young girls (and a few boys as well) from being sold to brothels by unsuspecting parents. Every child has a smart wallet where they can earn their own way in the bigger cities, so the traffickers are looking in more and more remote villages. However with technology moving faster than they are monitoring stations may soon be a thing of the past. The organization credits not just awareness, but their ability to raise funds directly within the Aragon interface.

In Thailand, elections are happening again. This time it is occurring on the blockchain to prevent any type of interference or tampering. There were concerns that the elderly would have trouble adapting to the new technology, but those fears were quite unfounded. The interface is designed to be “so easy a great grandmother can do it” and they can go to polling locations still if they find that they need help. The UN is monitoring the polling stations quite closely and each wallet is limited to one vote to prevent duplication or undue influence. The Diaspora are enjoying voting in real time.

In China the Aragon blockchain is helping young women show that they are just as valuable as men. They are quickly programming new products. “Higoli” is a new game created by one talented young artist. I tried to understand it but the young girls in Beijing thought it was too difficult to explain to an “out of touch” Westerner. The game has over a million players and a portion of the proceeds are going to fund an orphanage in the Western part of the country.

In Iran and Iraq the Kurds are using the Aragon chain to work to develop more independence within their current governments. Turkey quashing the idea of an independent Kurdistan (for now) quite firmly didn’t dash their ideals. The constitution for the new region and its freedoms aren’t just written in blood, but are also encoded in the blockchain to be protected for future generations. They joke that it is much cheaper than the way older nations preserved their constitution.

**Comment by yermoo** [comment]
Aragon Network will be the first decentralized organization governed by the community whose objective is to act as a digital jurisdiction, a decentralized online judicial system that is not subject to traditional artificial barriers such as national jurisdictions or the borders of a single country.

Aragon allows any decentralized economic organization to be constituted through the Dapp Aragon to create its Tokens, assign its tokens, make their votes, visualize their groups, check their finances and make payments all under the transparency of the Blockchain technology and under the Platform Ethereum

Currently, if a SME in India wants to sell products or provide services to a SME in Nigeria and another SME in Mexico it is very possible that (despite international laws) SMEs in India have to hire lawyers to advise them of the jurisdiction of each country Nigeria and Mexico that will be different.

Aragon will solve this problem because if the SMEs of India, Nigeria, Mexico are within the digital jurisdiction Aragon will have the same standards for all SMEs (decentralized organizations) that have been voted and legislated by the whole community Aragon .

Currently, if a SME in India wants to sell products or provide services to a SME in Spain, to ensure the collection of the sale of the company in India and ensure the reception in good condition of the merchandise the SME of Spain should use a third (most times a bank that manages the Collection against some documents) that supposes an additional cost in the sale of the product.

Aragon will solve this problem because both parties can initiate an intelligent contract that automatically executes the payment if the condition of the contract is met.

Today we have only exposed 3 solutions offered by Aragon to create a fairer world, we hope to tell you many more from our decentralized and autonomous community Aragon

**Comment by Smokyish** [comment]
@Zurpples Great work!

Could you please create [a new Pull Request](https://monthly.aragon.one/guides/guide_for_submitting_a_new_pull_request/) for your article so we can review it and so that you can claim the bounty for this!

> To claim this bounty sign up at https://openbounty.status.im and make sure to update your Ethereum address in My Payment Details so that the bounty is correctly allocated.

If you need help with the Pull Request, don't hesitate to ask, we are happy to help with the details, important thing is that you create the Pull Requets and that `Closes #8` is in the description so the bounty can be properly rewarded to you.
